# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: /scratch/s4367073/thesis/logs_nl/

checkpoint:
  save_dir: /scratch/s4367073/thesis/output_files_nl/
  save_interval: 50
  save_interval_updates: 1000
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: wer

task:
  _name: audio_finetuning
  data: /scratch/s4367073/thesis/manifest/
  normalize: true
  labels: ltr

dataset:
  num_workers: 6
  max_tokens: 500000           
  skip_invalid_size_inputs_valid_test: true
  validate_after_updates: 100
  validate_interval: 200
  valid_subset: valid

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 1

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  max_update: 10000
  lr: [0.0003]                 
  sentence_avg: true
  update_freq: [1]

optimizer:
  _name: adam
  adam_betas: (0.9, 0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.2

model:
  _name: wav2vec_ctc
  w2v_path: /scratch/s4367073/thesis/checkpoints/xlsr_53.pt
  apply_mask: true
  mask_prob: 0.1               
  mask_channel_prob: 0.05
  mask_channel_length: 32
  layerdrop: 0.0
  activation_dropout: 0.0
  feature_grad_mult: 0.0
  freeze_finetune_updates: 0  
